/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lanjutan;

/**
 *
 * @author tio
 */
public class Lanjutan1 extends javax.swing.JFrame {

    /**
     * Creates new form Lanjutan1
     */
    public Lanjutan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RPL = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Keluar = new javax.swing.JButton();
        Oke = new javax.swing.JButton();
        Alamat = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        Kelas = new javax.swing.JComboBox<>();
        rdb1 = new javax.swing.JRadioButton();
        rdb2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("NAMA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 70, 39, 16);

        jLabel2.setText("ALAMAT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 220, 60, 16);

        jLabel3.setText("JURUSAN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 180, 70, 16);

        jLabel4.setText("KELAS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 140, 38, 16);

        jLabel5.setText("ABSEN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 100, 40, 16);

        jLabel6.setText("BIODATA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 10, 80, 16);

        Keluar.setText("KELUAR");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(280, 280, 92, 50);

        Oke.setText("OKE");
        Oke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkeActionPerformed(evt);
            }
        });
        getContentPane().add(Oke);
        Oke.setBounds(140, 280, 75, 50);
        getContentPane().add(Alamat);
        Alamat.setBounds(130, 210, 280, 40);
        getContentPane().add(Nama);
        Nama.setBounds(130, 50, 280, 40);
        getContentPane().add(Absen);
        Absen.setBounds(130, 90, 280, 40);

        Kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X RPL 1", "X RPL 2", "X RPL 3", "X RPL 4", "X RPL 5", "X RPL 6", "X RPL 7", " " }));
        Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelasActionPerformed(evt);
            }
        });
        getContentPane().add(Kelas);
        Kelas.setBounds(130, 127, 280, 40);

        RPL.add(rdb1);
        rdb1.setText("RPL");
        getContentPane().add(rdb1);
        rdb1.setBounds(130, 180, 54, 20);

        RPL.add(rdb2);
        rdb2.setText("TKJ");
        rdb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb2);
        rdb2.setBounds(270, 180, 52, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/tio/Downloads/logo-ts.png")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-20, 0, 470, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb2ActionPerformed

    private void KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelasActionPerformed

    private void OkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkeActionPerformed
        // TODO add your handling code here:
        String nama = Nama.getText();
        String absen = Absen.getText();
        String kelas = Kelas.getSelectedItem().toString();
        String jurusan = "";
        String alamat = Alamat.getText();
        
        if(rdb1.isSelected())
            jurusan = "RPL";
        else if(rdb2.isSelected())
            jurusan = "TKJ";
        else
            
        if(Kelas.getSelectedItem()== "X RPL 1"){            
        }  
        if(Kelas.getSelectedItem()== "X RPL 2"){            
        }  
        if(Kelas.getSelectedItem()== "X RPL 3"){            
        }  
        if(Kelas.getSelectedItem()== "X RPL 4"){            
        }  
        if(Kelas.getSelectedItem()== "X RPL 5"){            
        }  
        if(Kelas.getSelectedItem()== "X RPL 6"){            
        }  
        if(Kelas.getSelectedItem()== "X RPL 7"){            
        }  
        new Lanjutan2(nama,absen,kelas,jurusan,alamat).setVisible(true);
    }//GEN-LAST:event_OkeActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lanjutan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lanjutan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lanjutan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lanjutan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lanjutan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextField Alamat;
    private javax.swing.JComboBox<String> Kelas;
    private javax.swing.JButton Keluar;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton Oke;
    private javax.swing.ButtonGroup RPL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rdb1;
    private javax.swing.JRadioButton rdb2;
    // End of variables declaration//GEN-END:variables
}
