/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KUIS;

/**
 *
 * @author tio
 */
public class Kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    public Kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Hg1 = new javax.swing.JTextField();
        Hg3 = new javax.swing.JTextField();
        Hg4 = new javax.swing.JTextField();
        Diskon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Hg2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Keluar = new javax.swing.JButton();
        Proses = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("DISKON");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 210, 70, 20);

        Hg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hg1ActionPerformed(evt);
            }
        });
        getContentPane().add(Hg1);
        Hg1.setBounds(100, 40, 240, 40);
        getContentPane().add(Hg3);
        Hg3.setBounds(100, 120, 240, 40);
        getContentPane().add(Hg4);
        Hg4.setBounds(100, 160, 240, 40);
        getContentPane().add(Diskon);
        Diskon.setBounds(100, 200, 240, 40);

        jLabel2.setText("HARGA 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 70, 20);

        Hg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hg2ActionPerformed(evt);
            }
        });
        getContentPane().add(Hg2);
        Hg2.setBounds(100, 80, 240, 40);

        jLabel3.setText("HARGA 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 70, 20);

        jLabel4.setText("HARGA 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 70, 20);

        jLabel5.setText("HARGA 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 170, 70, 20);

        Keluar.setText("KELUAR");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(240, 270, 92, 29);

        Proses.setText("PROSES");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        getContentPane().add(Proses);
        Proses.setBounds(30, 270, 90, 29);

        Hapus.setText("HAPUS");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus);
        Hapus.setBounds(130, 270, 86, 29);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 310, 244, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Hg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hg1ActionPerformed

    private void Hg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hg2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hg2ActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        TA.setText("");
        Hg1.setText("");
        Hg2.setText("");
        Hg3.setText("");
        Hg4.setText("");
        Diskon.setText("");
       
    }//GEN-LAST:event_HapusActionPerformed

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        // TODO add your handling code here:
        int hg1 = Integer.parseInt(Hg1.getText());
        int hg2 = Integer.parseInt(Hg2.getText());
        int hg3 = Integer.parseInt(Hg3.getText());
        int hg4 = Integer.parseInt(Hg4.getText());
        int diskon = Integer.parseInt(Diskon.getText());
        int hasil = hg1+hg2+hg3+hg4;
        int dskn = hasil*diskon/100;
        int total = hasil - dskn;
        TA.setText("Harga Barang 1 : "+hg1+"\n"+"Harga Barang 2 : "+hg2+"\n"+"Harga Barang 3 : "+hg3+"\n"+"Harga Barang 4 : "+hg4+
                "\n"+"Diskon Anda : "+diskon+"\n"+"TOTAL HARGA : "+hasil+"\n"+"TOTAL BAYAR : "+total);
        
    }//GEN-LAST:event_ProsesActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Diskon;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField Hg1;
    private javax.swing.JTextField Hg2;
    private javax.swing.JTextField Hg3;
    private javax.swing.JTextField Hg4;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Proses;
    private javax.swing.JTextArea TA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
